#pragma once

#include <ntddk.h>

#define VULNDR_DEVICE_NAME      L"\\Device\\VulnDr"
#define VULNDR_DOS_DEVICE_NAME  L"\\DosDevices\\VulnDr"
#define VULNDR_WIN32_NAME       L"\\\\.\\VulnDr"

#define VULNDR_FAKE_REGION_SIZE          256
#define VULNDR_FAKE_REGION_MAX_TRANSFER  64
#define VULNDR_VULN_DATA_SIZE 512

#define IOCTL_VULNDR_GET_VERSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_VULNDR_ECHO \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_VULNDR_GET_STATS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_VULNDR_SAFE_READ_FAKE_REGION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_VULNDR_SAFE_WRITE_FAKE_REGION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_VULNDR_VULN_STACK_OVERFLOW \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _VULNDR_VERSION_INFO
{
    unsigned long Major;
    unsigned long Minor;
    unsigned long Build;
    wchar_t Message[128];
} VULNDR_VERSION_INFO, * PVULNDR_VERSION_INFO;

typedef struct _VULNDR_ECHO_REQUEST
{
    unsigned long InputLength;
    char Input[128];
} VULNDR_ECHO_REQUEST, * PVULNDR_ECHO_REQUEST;

typedef struct _VULNDR_STATS
{
    long TotalIoctlsHandled;
} VULNDR_STATS, * PVULNDR_STATS;

typedef struct _VULNDR_FAKE_RW_REQUEST
{
    unsigned long Offset;
    unsigned long Size;
    unsigned char Data[VULNDR_FAKE_REGION_MAX_TRANSFER];
} VULNDR_FAKE_RW_REQUEST, * PVULNDR_FAKE_RW_REQUEST;

typedef struct _VULNDR_VULN_STACK_REQUEST
{
    unsigned long Size;
    unsigned char Data[VULNDR_VULN_DATA_SIZE];
} VULNDR_VULN_STACK_REQUEST, * PVULNDR_VULN_STACK_REQUEST;